#!/bin/bash

# Post-commit hook script to run main.py

# Path to main.py script
MAIN_SCRIPT="S:\CODES\PYTHON3.0\NLP\main.py"

# Log file path
LOG_FILE="S:\CODES\PYTHON3.0\NLP\log.txt"

# Get list of committed files
FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Loop through committed files
for FILE in $FILES
do
    # Check file extension
    EXTENSION="${FILE##*.}"
    case "$EXTENSION" in
        py|java|cpp|c|cs|js)
            # Run main.py for files with appropriate extensions and redirect output to log file
            python3 "$MAIN_SCRIPT" "$FILE" >> "$LOG_FILE"
            ;;
    esac
done

